# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Advanced Computer Vision Meetup
tagline:          ''
description:      ''
url: 'https://advancedcomputervision.github.io/'
baseurl:          ''

author:
  name:           'Advanced Computer Vision Meetup'
  url: https://github.com/advancedcomputervision

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo: https://github.com/advancedcomputervision/advancedcomputervision.github.io/tree/gh-pages

plugins:          [jekyll-paginate, jekyll-gist]
